local.tf, main.tf
일단 제가 생각하는데로 넣을거 넣고 빼야하는거 뺐는데 확인해주세요
=> 🔀 :: RDS import해서 추가

local.tf, main.tf, modules/eks-cluster/local.tf, modules/eks-cluster/main.tf, modules/eks-cluster/variables.tf
=> 🔀  ::  spot instance

modules/vpc/main.tf, modules/vpc/variables.tf, vpc.tf
비용 절감을 위해 Karpenter에서 참조하는 subnet tag를 하나의 subnet에만 달도록 수정했습니다
=> 🔀 :: subnet tag 하나에만 부여

.github/workflows/add_ecr.yaml
Step에 있는 name의 withh을 with으로 수정하였습니다.
=> Change step name "withh" to "with"

.github/workflows/update-helm-block.yaml
- PR명에 수정하는 Chart와 버전이 드러나도록 수정
- (암묵적인) 커밋 메시지 룰에 따라 형식 수정
=> 🔀️ :: 자동 버전업 Bot PR명 변경

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.24

helm.tf
=> 🔀 :: Update istio version to 1.0.40

helm.tf
=> 🔀 :: Update vault version to 1.0.1

helm.tf
=> 🔀 :: Update vault version to 1.0.2

helm.tf
=> 🔀 :: Update vault version to 1.0.3

helm.tf
=> 🔀 :: Update vault version to 1.0.4

helm.tf
=> 🔀 :: Update vault version to 1.0.5

helm.tf
=> 🔀 :: Update vault version to 1.0.6

helm.tf
=> 🔀 :: Update vault version to 1.0.7

helm.tf
=> 🔀 :: Update vault version to 1.0.8

helm.tf
=> 🔀 :: Update vault version to 1.0.10

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.25

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.26

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.27

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.28

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.29

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.30

helm.tf
=> 🔀 :: Update karpenter version to 1.0.36

helm.tf
=> 🔀 :: Update istio version to 1.0.42

helm.tf
=> 🔀 :: Update karpenter version to 1.0.37

helm.tf
=> 🔀 :: Update karpenter version to 1.0.38

helm.tf
=> 🔀 :: Update karpenter version to 1.0.39

helm.tf
=> 🔀 :: Update karpenter version to 1.0.41

helm.tf
=> 🔀 :: Update karpenter version to 1.0.42

helm.tf
=> 🔀 :: Update karpenter version to 1.0.43

helm.tf
=> 🔀 :: Update karpenter version to 1.0.44

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.31

helm.tf
=> 🔀 :: Update karpenter version to 1.0.45

helm.tf
=> 🔀 :: Update karpenter version to 1.0.47

helm.tf
=> 🔀 :: Update karpenter version to 1.0.48

helm.tf
=> 🔀 :: Update karpenter version to 1.0.49

helm.tf
=> 🔀 :: Update karpenter version to 1.0.50

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.32

helm.tf
=> 🔀 :: Update karpenter version to 1.0.51

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.33

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.34

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.35

helm.tf
=> 🔀 :: Update karpenter version to 1.0.52

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.36

helm.tf
=> 🔀 :: Update karpenter version to 1.0.53

helm.tf
=> 🔀 :: Update istio version to 1.0.43

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.37

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.38

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.39

helm.tf
=> 🔀 :: Update istio version to 1.0.44

helm.tf
=> 🔀 :: Update istio version to 1.0.45

helm.tf
=> 🔀 :: Update istio version to 1.0.46

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.42

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.43

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.44

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.45

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.46

helm.tf
=> 🔀 :: Update karpenter version to 1.0.54

helm.tf
=> 🔀 :: Update karpenter version to 1.0.55

helm.tf
=> 🔀 :: Update karpenter version to 1.0.57

helm.tf
=> 🔀 :: Update cert-manager version to v1.12.14

helm.tf
=> 🔀 :: Update istio version to 1.0.47

helm.tf
=> 🔀 :: Update istio version to 1.0.48

helm.tf
=> 🔀 :: Update karpenter version to 1.0.58

helm.tf
=> 🔀 :: Update karpenter version to 1.0.59

helm.tf
=> 🔀 :: Update karpenter version to 1.0.60

helm.tf
=> 🔀 :: Update karpenter version to 1.0.61

helm.tf
=> 🔀 :: Update karpenter version to 1.0.63

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.48

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.50

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.51

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.53

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.54

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.55

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.56

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.57

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.58

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.59

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.60

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.61

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.62

helm.tf
=> 🔀 :: Update istio version to 1.0.49

helm.tf
=> 🔀 :: Update istio version to 1.0.50

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.63

helm.tf
=> 🔀 :: Update karpenter version to 1.0.65

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.64

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.65

helm.tf
=> 🔀 :: Update xquare-application version to 1.0.66

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.0

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.1

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.2

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.3

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.4

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.5

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.6

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.7

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.8

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.9

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.10

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.12

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.13

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.14

helm.tf
=> 🔀 :: Update istio version to 1.1.0

helm.tf
=> 🔀 :: Update datadog version to 2.1.0

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.15

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.16

helm.tf
=> 🔀 :: Update datadog version to 2.2.1

helm.tf
=> 🔀 :: Update datadog version to 2.3.1

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.17

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.18

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.21

helm.tf
=> 🔀 :: Update cert-manager version to 2.0.0

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.22

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.23

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.24

helm.tf
=> 🔀 :: Update datadog version to 2.3.2

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.25

helm.tf
=> 🔀 :: Update istio version to 1.2.0

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.26

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.28

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.29

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.30

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.31

helm.tf
=> 🔀 :: Update xquare-application version to 1.1.32

helm.tf
=> 🔀 :: Update datadog version to 2.3.3

helm.tf
=> 🔀 :: Update datadog version to 2.3.4

helm.tf
=> 🔀 :: Update datadog version to 2.3.5

helm.tf
=> 🔀 :: Update datadog version to 2.3.6

helm.tf
=> 🔀 :: Update datadog version to 2.3.7

helm.tf
=> 🔀 :: Update datadog version to 2.3.8

helm.tf
=> 🔀 :: Update datadog version to 2.3.10

helm.tf
=> 🔀 :: Update datadog version to 2.3.11

helm.tf
=> 🔀 :: Update datadog version to 2.3.12

helm.tf
=> 🔀 :: Update datadog version to 2.3.13

helm.tf
=> 🔀 :: Update datadog version to 2.3.14

helm.tf
=> 🔀 :: Update datadog version to 2.3.15

helm.tf
=> 🔀 :: Update datadog version to 2.3.17

helm.tf
=> 🔀 :: Update datadog version to 2.3.18

helm.tf
=> 🔀 :: Update datadog version to 2.3.19

helm.tf
=> 🔀 :: Update datadog version to 2.3.20

helm.tf
=> 🔀 :: Update datadog version to 2.3.22

helm.tf
=> 🔀 :: Update datadog version to 2.3.25

helm.tf
=> 🔀 :: Update datadog version to 2.3.26

helm.tf
=> 🔀 :: Update datadog version to 2.3.27

helm.tf
=> 🔀 :: Update karpenter version to 1.0.67
